/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aircraft: typeof import('./src/modules/aircraft/views/Aircraft.vue')['default']
    AircraftForm: typeof import('./src/modules/aircraft/components/AircraftForm.vue')['default']
    AircraftModel: typeof import('./src/modules/aircraft/views/AircraftModel.vue')['default']
    AircraftTable: typeof import('./src/modules/aircraft/components/AircraftTable.vue')['default']
    Airline: typeof import('./src/modules/airline/views/Airline.vue')['default']
    AirlineForm: typeof import('./src/modules/airline/components/AirlineForm.vue')['default']
    AirlineTable: typeof import('./src/modules/airline/components/AirlineTable.vue')['default']
    Airport: typeof import('./src/modules/airport/views/Airport.vue')['default']
    AirportForm: typeof import('./src/modules/airport/components/AirportForm.vue')['default']
    AirportTable: typeof import('./src/modules/airport/components/AirportTable.vue')['default']
    App: typeof import('./src/App.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Confirm: typeof import('./src/shared/components/Confirm.vue')['default']
    DialogHost: typeof import('./src/plugins/dialog/DialogHost.vue')['default']
    DialogWrapper: typeof import('./src/plugins/dialog/DialogWrapper.vue')['default']
    Form: typeof import('./src/shared/components/Form.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    Manufacturer: typeof import('./src/modules/manufacturer/components/Manufacturer.vue')['default']
    ManufacturerForm: typeof import('./src/modules/manufacturer/components/ManufacturerForm.vue')['default']
    ManufacturerTable: typeof import('./src/modules/manufacturer/components/ManufacturerTable.vue')['default']
    ModelForm: typeof import('./src/modules/aircraft/components/model/ModelForm.vue')['default']
    ModelTable: typeof import('./src/modules/aircraft/components/model/ModelTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    SnackbarHost: typeof import('./src/plugins/snackbar/SnackbarHost.vue')['default']
  }
}
